export const alimentosSeed = [
  // ==================== LACTEOS ====================
  {
    nombre: 'Leche entera',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Leche',
    calorias: 63,
    proteinas: 3.1,
    carbohidratos: 4.7,
    grasas: 3.5,
    fibra: 0,
    racionIntercambio: 200,
    descripcionRacion: '1 vaso',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Leche desnatada',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Leche',
    calorias: 34,
    proteinas: 3.4,
    carbohidratos: 4.8,
    grasas: 0.1,
    fibra: 0,
    racionIntercambio: 200,
    descripcionRacion: '1 vaso',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Yogur natural',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Yogur',
    calorias: 61,
    proteinas: 3.5,
    carbohidratos: 4.7,
    grasas: 3.3,
    fibra: 0,
    racionIntercambio: 125,
    descripcionRacion: '1 unidad',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Queso fresco',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Queso',
    calorias: 174,
    proteinas: 11.3,
    carbohidratos: 2.5,
    grasas: 13.3,
    fibra: 0,
    racionIntercambio: 60,
    descripcionRacion: '2 lonchas',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Queso manchego',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Queso',
    calorias: 376,
    proteinas: 26.0,
    carbohidratos: 0.5,
    grasas: 30.0,
    fibra: 0,
    racionIntercambio: 30,
    descripcionRacion: '1 loncha gruesa',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Requesón',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Queso',
    calorias: 96,
    proteinas: 13.6,
    carbohidratos: 1.4,
    grasas: 4.3,
    fibra: 0,
    racionIntercambio: 100,
    descripcionRacion: '1 tarrina pequeña',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },

  // ==================== FRUTAS ====================
  {
    nombre: 'Manzana',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 52,
    proteinas: 0.3,
    carbohidratos: 13.8,
    grasas: 0.2,
    fibra: 2.4,
    racionIntercambio: 150,
    descripcionRacion: '1 unidad mediana',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño', 'invierno'],
  },
  {
    nombre: 'Plátano',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 89,
    proteinas: 1.1,
    carbohidratos: 22.8,
    grasas: 0.3,
    fibra: 2.6,
    racionIntercambio: 80,
    descripcionRacion: '1 unidad pequeña',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Naranja',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 47,
    proteinas: 0.9,
    carbohidratos: 11.7,
    grasas: 0.1,
    fibra: 2.4,
    racionIntercambio: 200,
    descripcionRacion: '1 unidad mediana',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['invierno', 'primavera'],
  },
  {
    nombre: 'Fresa',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 33,
    proteinas: 0.7,
    carbohidratos: 7.7,
    grasas: 0.3,
    fibra: 2.0,
    racionIntercambio: 200,
    descripcionRacion: '8-10 unidades',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['primavera'],
  },
  {
    nombre: 'Uva',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 69,
    proteinas: 0.7,
    carbohidratos: 18.1,
    grasas: 0.2,
    fibra: 0.9,
    racionIntercambio: 100,
    descripcionRacion: '1 racimo pequeño',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño'],
  },
  {
    nombre: 'Pera',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 57,
    proteinas: 0.4,
    carbohidratos: 15.2,
    grasas: 0.1,
    fibra: 3.1,
    racionIntercambio: 150,
    descripcionRacion: '1 unidad mediana',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño', 'invierno'],
  },
  {
    nombre: 'Melocotón',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 39,
    proteinas: 0.9,
    carbohidratos: 9.5,
    grasas: 0.3,
    fibra: 1.5,
    racionIntercambio: 200,
    descripcionRacion: '1 unidad mediana',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['verano'],
  },
  {
    nombre: 'Sandía',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 30,
    proteinas: 0.6,
    carbohidratos: 7.6,
    grasas: 0.2,
    fibra: 0.4,
    racionIntercambio: 250,
    descripcionRacion: '1 tajada',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['verano'],
  },
  {
    nombre: 'Melón',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 34,
    proteinas: 0.8,
    carbohidratos: 8.2,
    grasas: 0.2,
    fibra: 0.9,
    racionIntercambio: 250,
    descripcionRacion: '1 tajada',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['verano'],
  },
  {
    nombre: 'Kiwi',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 61,
    proteinas: 1.1,
    carbohidratos: 14.7,
    grasas: 0.5,
    fibra: 3.0,
    racionIntercambio: 100,
    descripcionRacion: '1 unidad',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['invierno', 'primavera'],
  },
  {
    nombre: 'Piña',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 50,
    proteinas: 0.5,
    carbohidratos: 13.1,
    grasas: 0.1,
    fibra: 1.4,
    racionIntercambio: 150,
    descripcionRacion: '2 rodajas',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Mandarina',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 53,
    proteinas: 0.8,
    carbohidratos: 13.3,
    grasas: 0.3,
    fibra: 1.8,
    racionIntercambio: 150,
    descripcionRacion: '2 unidades',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['invierno'],
  },

  // ==================== VERDURAS Y HORTALIZAS ====================
  {
    nombre: 'Tomate',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 18,
    proteinas: 0.9,
    carbohidratos: 3.9,
    grasas: 0.2,
    fibra: 1.2,
    racionIntercambio: 200,
    descripcionRacion: '1 unidad mediana',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['verano'],
  },
  {
    nombre: 'Lechuga',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 15,
    proteinas: 1.4,
    carbohidratos: 2.9,
    grasas: 0.2,
    fibra: 1.3,
    racionIntercambio: 100,
    descripcionRacion: '1 plato de ensalada',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Pepino',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 16,
    proteinas: 0.7,
    carbohidratos: 3.6,
    grasas: 0.1,
    fibra: 0.5,
    racionIntercambio: 200,
    descripcionRacion: '1 unidad',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['primavera', 'verano'],
  },
  {
    nombre: 'Zanahoria',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 41,
    proteinas: 0.9,
    carbohidratos: 9.6,
    grasas: 0.2,
    fibra: 2.8,
    racionIntercambio: 100,
    descripcionRacion: '1 unidad mediana',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Cebolla',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 40,
    proteinas: 1.1,
    carbohidratos: 9.3,
    grasas: 0.1,
    fibra: 1.7,
    racionIntercambio: 100,
    descripcionRacion: '1 unidad mediana',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Pimiento rojo',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 31,
    proteinas: 1.0,
    carbohidratos: 6.0,
    grasas: 0.3,
    fibra: 2.1,
    racionIntercambio: 150,
    descripcionRacion: '1 unidad',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['verano'],
  },
  {
    nombre: 'Pimiento verde',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 20,
    proteinas: 0.9,
    carbohidratos: 4.6,
    grasas: 0.2,
    fibra: 1.7,
    racionIntercambio: 150,
    descripcionRacion: '1 unidad',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['verano'],
  },
  {
    nombre: 'Espinacas',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 23,
    proteinas: 2.9,
    carbohidratos: 3.6,
    grasas: 0.4,
    fibra: 2.2,
    racionIntercambio: 200,
    descripcionRacion: '1 plato',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño', 'invierno', 'primavera'],
  },
  {
    nombre: 'Brócoli',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 34,
    proteinas: 2.8,
    carbohidratos: 6.6,
    grasas: 0.4,
    fibra: 2.6,
    racionIntercambio: 200,
    descripcionRacion: '1 plato',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño', 'invierno'],
  },
  {
    nombre: 'Calabacín',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 17,
    proteinas: 1.2,
    carbohidratos: 3.1,
    grasas: 0.3,
    fibra: 1.0,
    racionIntercambio: 200,
    descripcionRacion: '1 unidad mediana',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['primavera', 'verano'],
  },
  {
    nombre: 'Judías verdes',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 31,
    proteinas: 1.8,
    carbohidratos: 7.0,
    grasas: 0.1,
    fibra: 3.4,
    racionIntercambio: 200,
    descripcionRacion: '1 plato',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['primavera', 'verano'],
  },
  {
    nombre: 'Berenjena',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 25,
    proteinas: 1.0,
    carbohidratos: 5.9,
    grasas: 0.2,
    fibra: 3.0,
    racionIntercambio: 200,
    descripcionRacion: '1 unidad mediana',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['verano'],
  },
  {
    nombre: 'Champiñón',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: 'Setas',
    calorias: 22,
    proteinas: 3.1,
    carbohidratos: 3.3,
    grasas: 0.3,
    fibra: 1.0,
    racionIntercambio: 200,
    descripcionRacion: '6-8 unidades',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Ajo',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: 'Condimento',
    calorias: 149,
    proteinas: 6.4,
    carbohidratos: 33.1,
    grasas: 0.5,
    fibra: 2.1,
    racionIntercambio: 5,
    descripcionRacion: '1 diente',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },

  // ==================== CEREALES Y TUBERCULOS ====================
  {
    nombre: 'Arroz blanco',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Cereales',
    calorias: 130,
    proteinas: 2.7,
    carbohidratos: 28.2,
    grasas: 0.3,
    fibra: 0.4,
    racionIntercambio: 60,
    descripcionRacion: '3 cucharadas soperas en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Pan integral',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Pan',
    calorias: 247,
    proteinas: 13.0,
    carbohidratos: 41.3,
    grasas: 3.4,
    fibra: 6.8,
    racionIntercambio: 40,
    descripcionRacion: '2 rebanadas',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: true,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Pasta',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Cereales',
    calorias: 131,
    proteinas: 5.0,
    carbohidratos: 25.4,
    grasas: 1.1,
    fibra: 1.8,
    racionIntercambio: 60,
    descripcionRacion: '60g en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: true,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Patata',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Tubérculos',
    calorias: 77,
    proteinas: 2.0,
    carbohidratos: 17.5,
    grasas: 0.1,
    fibra: 2.2,
    racionIntercambio: 150,
    descripcionRacion: '1 unidad mediana',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Avena',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Cereales',
    calorias: 389,
    proteinas: 16.9,
    carbohidratos: 66.3,
    grasas: 6.9,
    fibra: 10.6,
    racionIntercambio: 30,
    descripcionRacion: '3 cucharadas soperas',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: true,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Pan blanco',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Pan',
    calorias: 265,
    proteinas: 9.4,
    carbohidratos: 49.1,
    grasas: 3.2,
    fibra: 2.7,
    racionIntercambio: 40,
    descripcionRacion: '2 rebanadas',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: true,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Maíz',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Cereales',
    calorias: 86,
    proteinas: 3.3,
    carbohidratos: 18.7,
    grasas: 1.4,
    fibra: 2.0,
    racionIntercambio: 100,
    descripcionRacion: '1 mazorca pequeña',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['verano'],
  },
  {
    nombre: 'Quinoa',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Pseudocereal',
    calorias: 120,
    proteinas: 4.4,
    carbohidratos: 21.3,
    grasas: 1.9,
    fibra: 2.8,
    racionIntercambio: 60,
    descripcionRacion: '3 cucharadas soperas en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
];
