export const alimentosSeed3 = [
  // ==================== LACTEOS ADICIONALES ====================
  {
    nombre: 'Leche semidesnatada',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Leche',
    calorias: 46,
    proteinas: 3.2,
    carbohidratos: 4.8,
    grasas: 1.6,
    fibra: 0,
    racionIntercambio: 200,
    descripcionRacion: '1 vaso',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Yogur griego',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Yogur',
    calorias: 97,
    proteinas: 9.0,
    carbohidratos: 3.6,
    grasas: 5.0,
    fibra: 0,
    racionIntercambio: 125,
    descripcionRacion: '1 unidad',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Queso de cabra',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Queso',
    calorias: 364,
    proteinas: 21.6,
    carbohidratos: 0.1,
    grasas: 30.5,
    fibra: 0,
    racionIntercambio: 30,
    descripcionRacion: '1 loncha gruesa',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Queso de Burgos',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Queso',
    calorias: 174,
    proteinas: 15.0,
    carbohidratos: 2.5,
    grasas: 11.0,
    fibra: 0,
    racionIntercambio: 60,
    descripcionRacion: '1 porción',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Kéfir',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Lácteos fermentados',
    calorias: 41,
    proteinas: 3.3,
    carbohidratos: 4.7,
    grasas: 1.0,
    fibra: 0,
    racionIntercambio: 200,
    descripcionRacion: '1 vaso',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Nata líquida',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Nata',
    calorias: 308,
    proteinas: 2.1,
    carbohidratos: 3.4,
    grasas: 31.7,
    fibra: 0,
    racionIntercambio: 30,
    descripcionRacion: '2 cucharadas soperas',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Queso mozzarella',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Queso',
    calorias: 280,
    proteinas: 27.5,
    carbohidratos: 3.1,
    grasas: 17.1,
    fibra: 0,
    racionIntercambio: 40,
    descripcionRacion: '1 bola pequeña',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },

  // ==================== FRUTAS ADICIONALES ====================
  {
    nombre: 'Cereza',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 63,
    proteinas: 1.1,
    carbohidratos: 16.0,
    grasas: 0.2,
    fibra: 2.1,
    racionIntercambio: 120,
    descripcionRacion: '15-20 cerezas',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['primavera', 'verano'],
  },
  {
    nombre: 'Ciruela',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 46,
    proteinas: 0.7,
    carbohidratos: 11.4,
    grasas: 0.3,
    fibra: 1.4,
    racionIntercambio: 150,
    descripcionRacion: '2-3 unidades',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['verano'],
  },
  {
    nombre: 'Albaricoque',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 48,
    proteinas: 1.4,
    carbohidratos: 11.1,
    grasas: 0.4,
    fibra: 2.0,
    racionIntercambio: 150,
    descripcionRacion: '3-4 unidades',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['verano'],
  },
  {
    nombre: 'Higo',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 74,
    proteinas: 0.8,
    carbohidratos: 19.2,
    grasas: 0.3,
    fibra: 2.9,
    racionIntercambio: 120,
    descripcionRacion: '2-3 higos',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['verano', 'otoño'],
  },
  {
    nombre: 'Granada',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 68,
    proteinas: 1.7,
    carbohidratos: 17.2,
    grasas: 1.2,
    fibra: 4.0,
    racionIntercambio: 100,
    descripcionRacion: '1 unidad pequeña',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño'],
  },
  {
    nombre: 'Mango',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 60,
    proteinas: 0.8,
    carbohidratos: 15.0,
    grasas: 0.4,
    fibra: 1.6,
    racionIntercambio: 120,
    descripcionRacion: 'medio mango',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['verano', 'otoño'],
  },
  {
    nombre: 'Papaya',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 43,
    proteinas: 0.5,
    carbohidratos: 10.8,
    grasas: 0.3,
    fibra: 1.7,
    racionIntercambio: 200,
    descripcionRacion: '1 porción grande',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Frambuesa',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 52,
    proteinas: 1.2,
    carbohidratos: 11.9,
    grasas: 0.7,
    fibra: 6.5,
    racionIntercambio: 125,
    descripcionRacion: '1 tarrina',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['verano'],
  },
  {
    nombre: 'Arándano',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 57,
    proteinas: 0.7,
    carbohidratos: 14.5,
    grasas: 0.3,
    fibra: 2.4,
    racionIntercambio: 125,
    descripcionRacion: '1 tarrina',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['verano'],
  },
  {
    nombre: 'Limón',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 29,
    proteinas: 1.1,
    carbohidratos: 9.3,
    grasas: 0.3,
    fibra: 2.8,
    racionIntercambio: 100,
    descripcionRacion: '1 unidad',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['invierno', 'primavera'],
  },
  {
    nombre: 'Pomelo',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 42,
    proteinas: 0.8,
    carbohidratos: 10.7,
    grasas: 0.1,
    fibra: 1.6,
    racionIntercambio: 200,
    descripcionRacion: 'medio pomelo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['invierno'],
  },
  {
    nombre: 'Caqui',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 70,
    proteinas: 0.6,
    carbohidratos: 18.6,
    grasas: 0.2,
    fibra: 3.6,
    racionIntercambio: 120,
    descripcionRacion: '1 unidad',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño'],
  },
  {
    nombre: 'Níspero',
    grupoIntercambio: 'FRUTAS',
    subgrupo: null,
    calorias: 47,
    proteinas: 0.4,
    carbohidratos: 12.1,
    grasas: 0.2,
    fibra: 1.7,
    racionIntercambio: 150,
    descripcionRacion: '3-4 unidades',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['primavera'],
  },

  // ==================== VERDURAS ADICIONALES ====================
  {
    nombre: 'Coliflor',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 25,
    proteinas: 1.9,
    carbohidratos: 5.0,
    grasas: 0.3,
    fibra: 2.0,
    racionIntercambio: 200,
    descripcionRacion: '1 plato',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño', 'invierno'],
  },
  {
    nombre: 'Col rizada (kale)',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 49,
    proteinas: 4.3,
    carbohidratos: 8.8,
    grasas: 0.9,
    fibra: 3.6,
    racionIntercambio: 100,
    descripcionRacion: '1 plato',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño', 'invierno'],
  },
  {
    nombre: 'Acelga',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 19,
    proteinas: 1.8,
    carbohidratos: 3.7,
    grasas: 0.2,
    fibra: 1.6,
    racionIntercambio: 200,
    descripcionRacion: '1 plato',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño', 'invierno', 'primavera'],
  },
  {
    nombre: 'Alcachofa',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 47,
    proteinas: 3.3,
    carbohidratos: 10.5,
    grasas: 0.2,
    fibra: 5.4,
    racionIntercambio: 150,
    descripcionRacion: '2 alcachofas medianas',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño', 'invierno', 'primavera'],
  },
  {
    nombre: 'Espárrago verde',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 20,
    proteinas: 2.2,
    carbohidratos: 3.9,
    grasas: 0.1,
    fibra: 2.1,
    racionIntercambio: 200,
    descripcionRacion: '6-8 espárragos',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['primavera'],
  },
  {
    nombre: 'Espárrago blanco',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 20,
    proteinas: 2.2,
    carbohidratos: 3.1,
    grasas: 0.2,
    fibra: 1.7,
    racionIntercambio: 200,
    descripcionRacion: '6-8 espárragos',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['primavera'],
  },
  {
    nombre: 'Puerro',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 61,
    proteinas: 1.5,
    carbohidratos: 14.2,
    grasas: 0.3,
    fibra: 1.8,
    racionIntercambio: 150,
    descripcionRacion: '1 puerro mediano',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño', 'invierno'],
  },
  {
    nombre: 'Remolacha',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 43,
    proteinas: 1.6,
    carbohidratos: 9.6,
    grasas: 0.2,
    fibra: 2.8,
    racionIntercambio: 150,
    descripcionRacion: '1 unidad mediana',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Rábano',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 16,
    proteinas: 0.7,
    carbohidratos: 3.4,
    grasas: 0.1,
    fibra: 1.6,
    racionIntercambio: 100,
    descripcionRacion: '5-6 rabanitos',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['primavera', 'verano'],
  },
  {
    nombre: 'Apio',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 16,
    proteinas: 0.7,
    carbohidratos: 3.0,
    grasas: 0.2,
    fibra: 1.6,
    racionIntercambio: 150,
    descripcionRacion: '2-3 tallos',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Nabo',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 28,
    proteinas: 0.9,
    carbohidratos: 6.4,
    grasas: 0.1,
    fibra: 1.8,
    racionIntercambio: 150,
    descripcionRacion: '1 nabo mediano',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño', 'invierno'],
  },
  {
    nombre: 'Calabaza',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 26,
    proteinas: 1.0,
    carbohidratos: 6.5,
    grasas: 0.1,
    fibra: 0.5,
    racionIntercambio: 200,
    descripcionRacion: '1 ración',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño', 'invierno'],
  },
  {
    nombre: 'Boniato',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Tubérculos',
    calorias: 86,
    proteinas: 1.6,
    carbohidratos: 20.1,
    grasas: 0.1,
    fibra: 3.0,
    racionIntercambio: 120,
    descripcionRacion: '1 boniato pequeño',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño', 'invierno'],
  },
  {
    nombre: 'Rúcula',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 25,
    proteinas: 2.6,
    carbohidratos: 3.7,
    grasas: 0.7,
    fibra: 1.6,
    racionIntercambio: 50,
    descripcionRacion: '1 puñado generoso',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['primavera', 'otoño'],
  },
  {
    nombre: 'Canónigos',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 21,
    proteinas: 2.0,
    carbohidratos: 3.6,
    grasas: 0.4,
    fibra: 1.5,
    racionIntercambio: 80,
    descripcionRacion: '1 bolsa pequeña',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Col lombarda',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: null,
    calorias: 31,
    proteinas: 1.4,
    carbohidratos: 7.4,
    grasas: 0.2,
    fibra: 2.1,
    racionIntercambio: 200,
    descripcionRacion: '1 plato',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño', 'invierno'],
  },
  {
    nombre: 'Setas variadas',
    grupoIntercambio: 'VERDURAS_HORTALIZAS',
    subgrupo: 'Setas',
    calorias: 22,
    proteinas: 3.1,
    carbohidratos: 3.3,
    grasas: 0.3,
    fibra: 1.0,
    racionIntercambio: 200,
    descripcionRacion: '1 plato',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño'],
  },

  // ==================== CEREALES Y TUBERCULOS ADICIONALES ====================
  {
    nombre: 'Arroz integral',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Cereales',
    calorias: 111,
    proteinas: 2.6,
    carbohidratos: 23.0,
    grasas: 0.9,
    fibra: 1.8,
    racionIntercambio: 60,
    descripcionRacion: '3 cucharadas soperas en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Cuscús',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Cereales',
    calorias: 112,
    proteinas: 3.8,
    carbohidratos: 23.2,
    grasas: 0.2,
    fibra: 1.4,
    racionIntercambio: 60,
    descripcionRacion: '60g en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: true,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Pasta integral',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Cereales',
    calorias: 124,
    proteinas: 5.3,
    carbohidratos: 23.5,
    grasas: 1.1,
    fibra: 3.9,
    racionIntercambio: 60,
    descripcionRacion: '60g en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: true,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Pan de centeno',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Pan',
    calorias: 259,
    proteinas: 8.5,
    carbohidratos: 48.3,
    grasas: 3.3,
    fibra: 5.8,
    racionIntercambio: 40,
    descripcionRacion: '2 rebanadas',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: true,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Tortitas de arroz',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Cereales',
    calorias: 387,
    proteinas: 8.0,
    carbohidratos: 81.0,
    grasas: 2.8,
    fibra: 4.2,
    racionIntercambio: 20,
    descripcionRacion: '2 tortitas',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Mijo',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Cereales',
    calorias: 378,
    proteinas: 11.0,
    carbohidratos: 72.8,
    grasas: 4.2,
    fibra: 8.5,
    racionIntercambio: 60,
    descripcionRacion: '3 cucharadas soperas en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Trigo sarraceno',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Pseudocereal',
    calorias: 343,
    proteinas: 13.3,
    carbohidratos: 71.5,
    grasas: 3.4,
    fibra: 10.0,
    racionIntercambio: 60,
    descripcionRacion: '3 cucharadas soperas en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },

  // ==================== CARNES ADICIONALES ====================
  {
    nombre: 'Conejo',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Carnes magras',
    calorias: 136,
    proteinas: 20.1,
    carbohidratos: 0.0,
    grasas: 6.0,
    fibra: 0.0,
    racionIntercambio: 100,
    descripcionRacion: '1 ración mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Cordero (pierna)',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Carnes semigrasa',
    calorias: 203,
    proteinas: 18.2,
    carbohidratos: 0.0,
    grasas: 14.2,
    fibra: 0.0,
    racionIntercambio: 100,
    descripcionRacion: '1 ración mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Solomillo de ternera',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Carnes magras',
    calorias: 118,
    proteinas: 22.0,
    carbohidratos: 0.0,
    grasas: 3.2,
    fibra: 0.0,
    racionIntercambio: 100,
    descripcionRacion: '1 filete mediano',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Chorizo',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Embutidos y fiambres',
    calorias: 455,
    proteinas: 24.1,
    carbohidratos: 2.0,
    grasas: 38.3,
    fibra: 0.0,
    racionIntercambio: 30,
    descripcionRacion: '3-4 rodajas',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Lomo embuchado',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Embutidos y fiambres',
    calorias: 186,
    proteinas: 33.0,
    carbohidratos: 0.5,
    grasas: 5.8,
    fibra: 0.0,
    racionIntercambio: 40,
    descripcionRacion: '3-4 lonchas',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Morcilla',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Embutidos y fiambres',
    calorias: 379,
    proteinas: 14.6,
    carbohidratos: 18.0,
    grasas: 27.8,
    fibra: 0.0,
    racionIntercambio: 50,
    descripcionRacion: '1 rodaja gruesa',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },

  // ==================== PESCADOS Y MARISCOS ADICIONALES ====================
  {
    nombre: 'Dorada',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Pescado blanco',
    calorias: 96,
    proteinas: 19.8,
    carbohidratos: 0.0,
    grasas: 1.8,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '1 ración mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: true,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Rape',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Pescado blanco',
    calorias: 76,
    proteinas: 14.8,
    carbohidratos: 0.0,
    grasas: 1.9,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '1 ración mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: true,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Lenguado',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Pescado blanco',
    calorias: 86,
    proteinas: 17.5,
    carbohidratos: 0.0,
    grasas: 1.8,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '1 ración mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: true,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Boquerón',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Pescado azul',
    calorias: 131,
    proteinas: 20.3,
    carbohidratos: 0.0,
    grasas: 5.2,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '8-10 boquerones',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: true,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['primavera', 'verano'],
  },
  {
    nombre: 'Caballa',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Pescado azul',
    calorias: 205,
    proteinas: 18.6,
    carbohidratos: 0.0,
    grasas: 13.9,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '1 ración mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: true,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['primavera', 'verano'],
  },
  {
    nombre: 'Trucha',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Pescado azul',
    calorias: 119,
    proteinas: 20.5,
    carbohidratos: 0.0,
    grasas: 3.5,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '1 trucha mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: true,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Calamar',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Marisco',
    calorias: 92,
    proteinas: 15.6,
    carbohidratos: 3.1,
    grasas: 1.4,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '1 ración mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: true,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Almejas',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Marisco',
    calorias: 74,
    proteinas: 12.8,
    carbohidratos: 2.2,
    grasas: 1.0,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '15-20 almejas',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: true,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Langostino',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Marisco',
    calorias: 90,
    proteinas: 18.9,
    carbohidratos: 0.2,
    grasas: 1.4,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '6-8 langostinos',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: true,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Sepia',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Marisco',
    calorias: 79,
    proteinas: 16.2,
    carbohidratos: 0.7,
    grasas: 0.7,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '1 ración mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: true,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Atún en conserva al natural',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Conservas',
    calorias: 103,
    proteinas: 23.6,
    carbohidratos: 0.0,
    grasas: 0.8,
    fibra: 0.0,
    racionIntercambio: 80,
    descripcionRacion: '1 lata pequeña escurrida',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: true,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },

  // ==================== GRASAS ADICIONALES ====================
  {
    nombre: 'Aceite de coco',
    grupoIntercambio: 'GRASAS',
    subgrupo: 'Aceites vegetales',
    calorias: 862,
    proteinas: 0.0,
    carbohidratos: 0.0,
    grasas: 100.0,
    fibra: 0.0,
    racionIntercambio: 10,
    descripcionRacion: '1 cucharada sopera',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Aceite de linaza',
    grupoIntercambio: 'GRASAS',
    subgrupo: 'Aceites vegetales',
    calorias: 884,
    proteinas: 0.0,
    carbohidratos: 0.0,
    grasas: 100.0,
    fibra: 0.0,
    racionIntercambio: 10,
    descripcionRacion: '1 cucharada sopera',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Tahini (pasta de sésamo)',
    grupoIntercambio: 'GRASAS',
    subgrupo: 'Grasas vegetales',
    calorias: 595,
    proteinas: 17.0,
    carbohidratos: 21.2,
    grasas: 53.8,
    fibra: 9.3,
    racionIntercambio: 15,
    descripcionRacion: '1 cucharada sopera',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },

  // ==================== LEGUMBRES ADICIONALES ====================
  {
    nombre: 'Soja texturizada',
    grupoIntercambio: 'LEGUMBRES',
    subgrupo: null,
    calorias: 336,
    proteinas: 50.0,
    carbohidratos: 30.0,
    grasas: 1.2,
    fibra: 17.5,
    racionIntercambio: 30,
    descripcionRacion: '30g en seco',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: true,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Tofu',
    grupoIntercambio: 'LEGUMBRES',
    subgrupo: null,
    calorias: 76,
    proteinas: 8.1,
    carbohidratos: 1.9,
    grasas: 4.8,
    fibra: 0.3,
    racionIntercambio: 125,
    descripcionRacion: '1 bloque pequeño',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: true,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Edamame',
    grupoIntercambio: 'LEGUMBRES',
    subgrupo: null,
    calorias: 121,
    proteinas: 11.9,
    carbohidratos: 8.6,
    grasas: 5.2,
    fibra: 5.2,
    racionIntercambio: 80,
    descripcionRacion: '1 ración',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: true,
    temporada: ['todo el año'],
  },

  // ==================== BEBIDAS Y OTROS ====================
  {
    nombre: 'Bebida de avena',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Bebidas vegetales',
    calorias: 43,
    proteinas: 0.3,
    carbohidratos: 6.7,
    grasas: 1.5,
    fibra: 0.8,
    racionIntercambio: 200,
    descripcionRacion: '1 vaso',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: true,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Bebida de soja',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Bebidas vegetales',
    calorias: 33,
    proteinas: 2.9,
    carbohidratos: 0.6,
    grasas: 1.8,
    fibra: 0.6,
    racionIntercambio: 200,
    descripcionRacion: '1 vaso',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: true,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Bebida de almendras',
    grupoIntercambio: 'LACTEOS',
    subgrupo: 'Bebidas vegetales',
    calorias: 24,
    proteinas: 0.5,
    carbohidratos: 3.0,
    grasas: 1.1,
    fibra: 0.3,
    racionIntercambio: 200,
    descripcionRacion: '1 vaso',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: true,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Miel',
    grupoIntercambio: 'CEREALES_TUBERCULOS',
    subgrupo: 'Azúcares',
    calorias: 304,
    proteinas: 0.3,
    carbohidratos: 82.4,
    grasas: 0.0,
    fibra: 0.2,
    racionIntercambio: 15,
    descripcionRacion: '1 cucharada sopera',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Chocolate negro 85%',
    grupoIntercambio: 'GRASAS',
    subgrupo: 'Otros',
    calorias: 580,
    proteinas: 12.0,
    carbohidratos: 19.0,
    grasas: 46.0,
    fibra: 13.0,
    racionIntercambio: 20,
    descripcionRacion: '2-3 onzas',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Dátil',
    grupoIntercambio: 'FRUTAS',
    subgrupo: 'Fruta desecada',
    calorias: 277,
    proteinas: 1.8,
    carbohidratos: 75.0,
    grasas: 0.2,
    fibra: 6.7,
    racionIntercambio: 30,
    descripcionRacion: '2-3 dátiles',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Pasas',
    grupoIntercambio: 'FRUTAS',
    subgrupo: 'Fruta desecada',
    calorias: 299,
    proteinas: 3.1,
    carbohidratos: 79.2,
    grasas: 0.5,
    fibra: 3.7,
    racionIntercambio: 30,
    descripcionRacion: '1 puñado pequeño',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Orejones de albaricoque',
    grupoIntercambio: 'FRUTAS',
    subgrupo: 'Fruta desecada',
    calorias: 241,
    proteinas: 3.4,
    carbohidratos: 62.6,
    grasas: 0.5,
    fibra: 7.3,
    racionIntercambio: 30,
    descripcionRacion: '4-5 orejones',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
];
