export const alimentosSeed2 = [
  // ==================== LEGUMBRES ====================
  {
    nombre: 'Lentejas',
    grupoIntercambio: 'LEGUMBRES',
    subgrupo: null,
    calorias: 353,
    proteinas: 24.6,
    carbohidratos: 54.0,
    grasas: 1.1,
    fibra: 10.7,
    racionIntercambio: 60,
    descripcionRacion: '3 cucharadas soperas en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Garbanzos',
    grupoIntercambio: 'LEGUMBRES',
    subgrupo: null,
    calorias: 364,
    proteinas: 19.3,
    carbohidratos: 55.0,
    grasas: 5.0,
    fibra: 15.5,
    racionIntercambio: 60,
    descripcionRacion: '3 cucharadas soperas en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Alubias blancas',
    grupoIntercambio: 'LEGUMBRES',
    subgrupo: null,
    calorias: 333,
    proteinas: 21.1,
    carbohidratos: 52.5,
    grasas: 1.6,
    fibra: 15.2,
    racionIntercambio: 60,
    descripcionRacion: '3 cucharadas soperas en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Judiones',
    grupoIntercambio: 'LEGUMBRES',
    subgrupo: null,
    calorias: 329,
    proteinas: 20.2,
    carbohidratos: 50.8,
    grasas: 1.4,
    fibra: 14.0,
    racionIntercambio: 60,
    descripcionRacion: '3 cucharadas soperas en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Guisantes',
    grupoIntercambio: 'LEGUMBRES',
    subgrupo: null,
    calorias: 341,
    proteinas: 24.5,
    carbohidratos: 49.0,
    grasas: 1.2,
    fibra: 16.6,
    racionIntercambio: 60,
    descripcionRacion: '3 cucharadas soperas en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Lentejas rojas',
    grupoIntercambio: 'LEGUMBRES',
    subgrupo: null,
    calorias: 358,
    proteinas: 25.4,
    carbohidratos: 56.3,
    grasas: 1.3,
    fibra: 7.4,
    racionIntercambio: 60,
    descripcionRacion: '3 cucharadas soperas en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Habas secas',
    grupoIntercambio: 'LEGUMBRES',
    subgrupo: null,
    calorias: 341,
    proteinas: 26.1,
    carbohidratos: 46.0,
    grasas: 1.5,
    fibra: 13.1,
    racionIntercambio: 60,
    descripcionRacion: '3 cucharadas soperas en crudo',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },

  // ==================== CARNES, PESCADOS Y HUEVOS ====================
  {
    nombre: 'Pechuga de pollo',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Carnes magras',
    calorias: 165,
    proteinas: 31.0,
    carbohidratos: 0.0,
    grasas: 3.6,
    fibra: 0.0,
    racionIntercambio: 100,
    descripcionRacion: '1 filete mediano',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Ternera',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Carnes magras',
    calorias: 131,
    proteinas: 22.0,
    carbohidratos: 0.0,
    grasas: 4.8,
    fibra: 0.0,
    racionIntercambio: 100,
    descripcionRacion: '1 filete mediano',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Cerdo',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Carnes magras',
    calorias: 143,
    proteinas: 26.2,
    carbohidratos: 0.0,
    grasas: 3.5,
    fibra: 0.0,
    racionIntercambio: 100,
    descripcionRacion: '1 filete mediano',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Chuleta de cerdo',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Carnes semigrasa',
    calorias: 215,
    proteinas: 22.4,
    carbohidratos: 0.0,
    grasas: 13.8,
    fibra: 0.0,
    racionIntercambio: 100,
    descripcionRacion: '1 chuleta mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Huevo',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Huevos',
    calorias: 155,
    proteinas: 13.0,
    carbohidratos: 1.1,
    grasas: 11.0,
    fibra: 0.0,
    racionIntercambio: 60,
    descripcionRacion: '1 huevo mediano',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: true,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Salmón',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Pescado azul',
    calorias: 208,
    proteinas: 20.4,
    carbohidratos: 0.0,
    grasas: 13.6,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '1 rodaja mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: true,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Merluza',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Pescado blanco',
    calorias: 82,
    proteinas: 17.2,
    carbohidratos: 0.0,
    grasas: 1.3,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '1 rodaja mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: true,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Atún',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Pescado azul',
    calorias: 144,
    proteinas: 23.3,
    carbohidratos: 0.0,
    grasas: 4.9,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '1 rodaja mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: true,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['primavera', 'verano'],
  },
  {
    nombre: 'Sardinas',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Pescado azul',
    calorias: 208,
    proteinas: 24.6,
    carbohidratos: 0.0,
    grasas: 11.5,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '4-5 sardinas medianas',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: true,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['primavera', 'verano'],
  },
  {
    nombre: 'Gambas',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Marisco',
    calorias: 99,
    proteinas: 20.3,
    carbohidratos: 0.2,
    grasas: 1.7,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '8-10 gambas medianas',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: true,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Pulpo',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Marisco',
    calorias: 82,
    proteinas: 14.9,
    carbohidratos: 2.2,
    grasas: 1.0,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '1 ración mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: true,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Jamón serrano',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Embutidos y fiambres',
    calorias: 241,
    proteinas: 31.0,
    carbohidratos: 0.0,
    grasas: 12.8,
    fibra: 0.0,
    racionIntercambio: 40,
    descripcionRacion: '2-3 lonchas finas',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Jamón york',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Embutidos y fiambres',
    calorias: 131,
    proteinas: 18.4,
    carbohidratos: 1.5,
    grasas: 5.8,
    fibra: 0.0,
    racionIntercambio: 40,
    descripcionRacion: '2-3 lonchas',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Pavo',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Carnes magras',
    calorias: 135,
    proteinas: 30.0,
    carbohidratos: 0.0,
    grasas: 1.2,
    fibra: 0.0,
    racionIntercambio: 100,
    descripcionRacion: '1 filete mediano',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Muslo de pollo',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Carnes semigrasa',
    calorias: 177,
    proteinas: 24.2,
    carbohidratos: 0.0,
    grasas: 8.4,
    fibra: 0.0,
    racionIntercambio: 100,
    descripcionRacion: '1 muslo mediano sin piel',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Bacalao fresco',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Pescado blanco',
    calorias: 82,
    proteinas: 18.0,
    carbohidratos: 0.0,
    grasas: 0.7,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '1 trozo mediano',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: true,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Lubina',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Pescado blanco',
    calorias: 97,
    proteinas: 18.4,
    carbohidratos: 0.0,
    grasas: 2.5,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '1 ración mediana',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: true,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Mejillones',
    grupoIntercambio: 'CARNES_PESCADOS_HUEVOS',
    subgrupo: 'Marisco',
    calorias: 86,
    proteinas: 11.9,
    carbohidratos: 3.7,
    grasas: 2.2,
    fibra: 0.0,
    racionIntercambio: 130,
    descripcionRacion: '15-20 mejillones',
    esAptoVegetariano: false,
    esAptoVegano: false,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: true,
    contieneSoja: false,
    temporada: ['otoño', 'invierno'],
  },

  // ==================== GRASAS ====================
  {
    nombre: 'Aceite de oliva virgen extra',
    grupoIntercambio: 'GRASAS',
    subgrupo: 'Aceites vegetales',
    calorias: 884,
    proteinas: 0.0,
    carbohidratos: 0.0,
    grasas: 100.0,
    fibra: 0.0,
    racionIntercambio: 10,
    descripcionRacion: '1 cucharada sopera',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Mantequilla',
    grupoIntercambio: 'GRASAS',
    subgrupo: 'Grasas animales',
    calorias: 717,
    proteinas: 0.9,
    carbohidratos: 0.1,
    grasas: 81.1,
    fibra: 0.0,
    racionIntercambio: 12,
    descripcionRacion: '1 porción individual',
    esAptoVegetariano: true,
    esAptoVegano: false,
    contieneLactosa: true,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Aguacate',
    grupoIntercambio: 'GRASAS',
    subgrupo: 'Grasas vegetales',
    calorias: 160,
    proteinas: 2.0,
    carbohidratos: 8.5,
    grasas: 14.7,
    fibra: 6.7,
    racionIntercambio: 70,
    descripcionRacion: 'medio aguacate',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['otoño', 'invierno'],
  },
  {
    nombre: 'Aceitunas',
    grupoIntercambio: 'GRASAS',
    subgrupo: 'Grasas vegetales',
    calorias: 145,
    proteinas: 1.0,
    carbohidratos: 3.8,
    grasas: 13.9,
    fibra: 3.3,
    racionIntercambio: 30,
    descripcionRacion: '8-10 aceitunas',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Aceitunas negras',
    grupoIntercambio: 'GRASAS',
    subgrupo: 'Grasas vegetales',
    calorias: 115,
    proteinas: 0.8,
    carbohidratos: 6.3,
    grasas: 10.7,
    fibra: 3.2,
    racionIntercambio: 30,
    descripcionRacion: '8-10 aceitunas',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Aceite de girasol',
    grupoIntercambio: 'GRASAS',
    subgrupo: 'Aceites vegetales',
    calorias: 884,
    proteinas: 0.0,
    carbohidratos: 0.0,
    grasas: 100.0,
    fibra: 0.0,
    racionIntercambio: 10,
    descripcionRacion: '1 cucharada sopera',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },

  // ==================== FRUTOS SECOS ====================
  {
    nombre: 'Almendras',
    grupoIntercambio: 'FRUTOS_SECOS',
    subgrupo: null,
    calorias: 579,
    proteinas: 21.2,
    carbohidratos: 21.6,
    grasas: 49.9,
    fibra: 12.5,
    racionIntercambio: 20,
    descripcionRacion: '15-20 almendras',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: true,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Nueces',
    grupoIntercambio: 'FRUTOS_SECOS',
    subgrupo: null,
    calorias: 654,
    proteinas: 15.2,
    carbohidratos: 13.7,
    grasas: 65.2,
    fibra: 6.7,
    racionIntercambio: 20,
    descripcionRacion: '4-5 nueces enteras',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: true,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Avellanas',
    grupoIntercambio: 'FRUTOS_SECOS',
    subgrupo: null,
    calorias: 628,
    proteinas: 15.0,
    carbohidratos: 16.7,
    grasas: 60.8,
    fibra: 9.7,
    racionIntercambio: 20,
    descripcionRacion: '15-18 avellanas',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: true,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Pistachos',
    grupoIntercambio: 'FRUTOS_SECOS',
    subgrupo: null,
    calorias: 560,
    proteinas: 20.2,
    carbohidratos: 27.2,
    grasas: 45.3,
    fibra: 10.6,
    racionIntercambio: 20,
    descripcionRacion: '25-30 pistachos',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: true,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Semillas de chía',
    grupoIntercambio: 'FRUTOS_SECOS',
    subgrupo: 'Semillas',
    calorias: 486,
    proteinas: 16.5,
    carbohidratos: 42.1,
    grasas: 30.7,
    fibra: 34.4,
    racionIntercambio: 15,
    descripcionRacion: '1 cucharada sopera',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Semillas de lino',
    grupoIntercambio: 'FRUTOS_SECOS',
    subgrupo: 'Semillas',
    calorias: 534,
    proteinas: 18.3,
    carbohidratos: 28.9,
    grasas: 42.2,
    fibra: 27.3,
    racionIntercambio: 15,
    descripcionRacion: '1 cucharada sopera',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Piñones',
    grupoIntercambio: 'FRUTOS_SECOS',
    subgrupo: null,
    calorias: 673,
    proteinas: 13.7,
    carbohidratos: 13.1,
    grasas: 68.4,
    fibra: 3.7,
    racionIntercambio: 20,
    descripcionRacion: '2 cucharadas soperas',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: true,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Anacardos',
    grupoIntercambio: 'FRUTOS_SECOS',
    subgrupo: null,
    calorias: 553,
    proteinas: 18.2,
    carbohidratos: 30.2,
    grasas: 43.9,
    fibra: 3.3,
    racionIntercambio: 20,
    descripcionRacion: '15-18 anacardos',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: true,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Semillas de calabaza',
    grupoIntercambio: 'FRUTOS_SECOS',
    subgrupo: 'Semillas',
    calorias: 559,
    proteinas: 30.2,
    carbohidratos: 10.7,
    grasas: 49.1,
    fibra: 6.0,
    racionIntercambio: 15,
    descripcionRacion: '1 cucharada sopera',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
  {
    nombre: 'Semillas de girasol',
    grupoIntercambio: 'FRUTOS_SECOS',
    subgrupo: 'Semillas',
    calorias: 584,
    proteinas: 20.8,
    carbohidratos: 20.0,
    grasas: 51.5,
    fibra: 8.6,
    racionIntercambio: 15,
    descripcionRacion: '1 cucharada sopera',
    esAptoVegetariano: true,
    esAptoVegano: true,
    contieneLactosa: false,
    contieneGluten: false,
    contieneFrutosSecos: false,
    contieneHuevo: false,
    contienePescado: false,
    contieneMarisco: false,
    contieneSoja: false,
    temporada: ['todo el año'],
  },
];
