export const recetasSeed = [
  {
    nombre: 'Gazpacho andaluz',
    descripcion:
      'Sopa fría tradicional de Andalucía, perfecta para los meses de verano. Elaborada con hortalizas frescas y aceite de oliva virgen extra.',
    instrucciones:
      '1. Lavar y trocear los tomates, el pepino, el pimiento, la cebolla y el ajo.\n2. Introducir todas las verduras en el vaso de la batidora.\n3. Añadir el aceite de oliva virgen extra, el vinagre y la sal.\n4. Triturar hasta obtener una textura fina y homogénea.\n5. Colar si se desea una textura más fina.\n6. Refrigerar durante al menos 2 horas antes de servir.\n7. Servir frío con tropezones de pepino, pimiento y cebolla picados.',
    tiempoPreparacion: 20,
    tiempoCoccion: 0,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Sopas y cremas',
    estiloEspanol: true,
    region: 'Andalucía',
    caloriasPorRacion: 120,
    proteinasPorRacion: 2,
    carbohidratosPorRacion: 10,
    grasasPorRacion: 8,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Tomate', cantidad: 500, unidad: 'g', notas: 'maduros' },
      { alimentoNombre: 'Pepino', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Pimiento verde', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 50, unidad: 'g' },
      { alimentoNombre: 'Ajo', cantidad: 5, unidad: 'g', notas: '1 diente' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 40, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Tortilla española',
    descripcion:
      'La tortilla de patatas es uno de los platos más emblemáticos de la cocina española. Jugosa por dentro y dorada por fuera.',
    instrucciones:
      '1. Pelar y cortar las patatas en láminas finas.\n2. Pelar y cortar la cebolla en juliana fina.\n3. Calentar abundante aceite de oliva en una sartén y freír las patatas a fuego medio junto con la cebolla hasta que estén tiernas (unos 20 minutos).\n4. Escurrir bien el aceite sobrante.\n5. Batir los huevos en un bol grande con una pizca de sal.\n6. Mezclar las patatas y la cebolla con los huevos batidos.\n7. Calentar un poco de aceite en una sartén antiadherente y verter la mezcla.\n8. Cocinar a fuego medio-bajo durante 5 minutos.\n9. Dar la vuelta con la ayuda de un plato y cocinar otros 3-4 minutos.\n10. Servir templada o a temperatura ambiente.',
    tiempoPreparacion: 15,
    tiempoCoccion: 30,
    dificultad: 'media',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Platos principales',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 320,
    proteinasPorRacion: 14,
    carbohidratosPorRacion: 28,
    grasasPorRacion: 18,
    esAptoVegetariano: true,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Patata', cantidad: 400, unidad: 'g' },
      { alimentoNombre: 'Huevo', cantidad: 240, unidad: 'g', notas: '4 huevos' },
      { alimentoNombre: 'Cebolla', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 60, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Ensalada mediterránea',
    descripcion:
      'Ensalada fresca y colorida con ingredientes típicos de la dieta mediterránea. Ligera y nutritiva.',
    instrucciones:
      '1. Lavar y escurrir la lechuga, cortarla en trozos.\n2. Cortar los tomates en gajos.\n3. Pelar y cortar el pepino en rodajas.\n4. Cortar el aguacate por la mitad, retirar el hueso y cortarlo en láminas.\n5. Añadir las aceitunas.\n6. Disponer todos los ingredientes en una fuente.\n7. Aliñar con aceite de oliva virgen extra y sal al gusto.\n8. Servir inmediatamente.',
    tiempoPreparacion: 15,
    tiempoCoccion: 0,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Ensaladas',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 180,
    proteinasPorRacion: 3,
    carbohidratosPorRacion: 8,
    grasasPorRacion: 15,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Lechuga', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Tomate', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Pepino', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Aguacate', cantidad: 150, unidad: 'g', notas: '1 aguacate' },
      { alimentoNombre: 'Aceitunas', cantidad: 60, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Pollo al ajillo',
    descripcion:
      'Receta clásica de la cocina española. El pollo se cocina lentamente en aceite de oliva con abundante ajo, resultando tierno y muy aromático.',
    instrucciones:
      '1. Cortar la pechuga de pollo en trozos medianos y salpimentar.\n2. Pelar y laminar los ajos.\n3. Calentar el aceite de oliva en una cazuela o sartén amplia.\n4. Dorar los ajos laminados hasta que estén ligeramente dorados y reservar.\n5. En el mismo aceite, sellar los trozos de pollo por todos los lados a fuego fuerte.\n6. Bajar el fuego, incorporar los ajos reservados.\n7. Añadir un chorro de vino blanco (opcional) y dejar reducir.\n8. Tapar y cocinar a fuego lento durante 15-20 minutos hasta que el pollo esté bien hecho.\n9. Servir caliente con su propia salsa.',
    tiempoPreparacion: 10,
    tiempoCoccion: 25,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Platos principales',
    estiloEspanol: true,
    region: 'Castilla',
    caloriasPorRacion: 280,
    proteinasPorRacion: 35,
    carbohidratosPorRacion: 2,
    grasasPorRacion: 14,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Pechuga de pollo', cantidad: 600, unidad: 'g' },
      { alimentoNombre: 'Ajo', cantidad: 30, unidad: 'g', notas: '6-8 dientes' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 50, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Lentejas estofadas',
    descripcion:
      'Guiso tradicional español de lentejas con verduras. Un plato reconfortante, económico y muy nutritivo, ideal para los meses fríos.',
    instrucciones:
      '1. Lavar las lentejas bajo el grifo y escurrir.\n2. Pelar y picar la zanahoria, la patata, la cebolla y el ajo.\n3. Cortar el pimiento verde en trozos pequeños.\n4. En una olla grande, calentar el aceite de oliva y sofreír la cebolla, el ajo y el pimiento durante 5 minutos.\n5. Añadir la zanahoria y la patata, y sofreír 2 minutos más.\n6. Incorporar las lentejas y cubrir con agua fría (el doble de volumen que las lentejas).\n7. Llevar a ebullición y bajar el fuego.\n8. Cocinar a fuego lento durante 30-40 minutos hasta que las lentejas estén tiernas.\n9. Rectificar de sal y servir caliente.',
    tiempoPreparacion: 15,
    tiempoCoccion: 40,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO'],
    categoria: 'Legumbres',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 350,
    proteinasPorRacion: 22,
    carbohidratosPorRacion: 48,
    grasasPorRacion: 8,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Lentejas', cantidad: 300, unidad: 'g' },
      { alimentoNombre: 'Zanahoria', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Patata', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Pimiento verde', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Ajo', cantidad: 5, unidad: 'g', notas: '1 diente' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Merluza a la plancha con verduras',
    descripcion:
      'Merluza fresca a la plancha acompañada de verduras salteadas. Un plato ligero, saludable y muy sabroso.',
    instrucciones:
      '1. Salpimentar los lomos de merluza.\n2. Lavar y cortar el calabacín en rodajas, el brócoli en ramilletes y las judías verdes en trozos.\n3. Hervir o cocer al vapor el brócoli y las judías verdes durante 5-6 minutos. Escurrir.\n4. En una sartén con un poco de aceite, saltear el calabacín hasta que esté dorado.\n5. Añadir el brócoli y las judías verdes al salteado y mantener caliente.\n6. En otra sartén con aceite de oliva caliente, cocinar la merluza 3-4 minutos por cada lado.\n7. Servir la merluza sobre la cama de verduras.\n8. Aliñar con un chorrito de aceite de oliva virgen extra en crudo.',
    tiempoPreparacion: 10,
    tiempoCoccion: 15,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Pescados',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 220,
    proteinasPorRacion: 28,
    carbohidratosPorRacion: 8,
    grasasPorRacion: 9,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Merluza', cantidad: 500, unidad: 'g', notas: '4 lomos' },
      { alimentoNombre: 'Calabacín', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Brócoli', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Judías verdes', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Garbanzos con espinacas',
    descripcion:
      'Plato típico de la cocina andaluza y sevillana. Un guiso de cuaresma sencillo, saciante y lleno de sabor gracias al pimentón y el comino.',
    instrucciones:
      '1. Si se usan garbanzos secos, ponerlos en remojo la noche anterior y cocerlos hasta que estén tiernos. También se pueden usar garbanzos de bote escurridos.\n2. Lavar bien las espinacas.\n3. Pelar y picar la cebolla y los ajos.\n4. En una cazuela, calentar el aceite de oliva y sofreír la cebolla hasta que esté transparente.\n5. Añadir el ajo picado y cocinar 1 minuto más.\n6. Incorporar el tomate rallado y cocinar 5 minutos.\n7. Añadir las espinacas y dejar que se cocinen hasta que se reduzcan.\n8. Incorporar los garbanzos cocidos y un poco de caldo de su cocción.\n9. Sazonar con pimentón, comino y sal.\n10. Cocinar todo junto a fuego lento durante 10 minutos para que se integren los sabores.',
    tiempoPreparacion: 15,
    tiempoCoccion: 20,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Legumbres',
    estiloEspanol: true,
    region: 'Andalucía',
    caloriasPorRacion: 310,
    proteinasPorRacion: 18,
    carbohidratosPorRacion: 38,
    grasasPorRacion: 10,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Garbanzos', cantidad: 350, unidad: 'g', notas: 'cocidos o de bote' },
      { alimentoNombre: 'Espinacas', cantidad: 300, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Ajo', cantidad: 10, unidad: 'g', notas: '2 dientes' },
      { alimentoNombre: 'Tomate', cantidad: 100, unidad: 'g', notas: 'rallado' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Salmón al horno con patatas',
    descripcion:
      'Salmón jugoso horneado sobre una cama de patatas. Un plato completo, elegante y fácil de preparar que es rico en omega-3.',
    instrucciones:
      '1. Precalentar el horno a 200°C.\n2. Pelar las patatas y cortarlas en rodajas finas.\n3. Cortar la cebolla en aros finos.\n4. Disponer las patatas y la cebolla en una fuente de horno, aliñar con aceite de oliva y sal.\n5. Hornear las patatas durante 25 minutos a 200°C.\n6. Salpimentar los lomos de salmón.\n7. Colocar el salmón sobre las patatas y regar con un poco de aceite.\n8. Hornear 12-15 minutos más hasta que el salmón esté hecho pero jugoso.\n9. Servir directamente de la fuente.',
    tiempoPreparacion: 15,
    tiempoCoccion: 40,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Pescados',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 420,
    proteinasPorRacion: 32,
    carbohidratosPorRacion: 30,
    grasasPorRacion: 20,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Salmón', cantidad: 500, unidad: 'g', notas: '4 lomos' },
      { alimentoNombre: 'Patata', cantidad: 400, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Pisto manchego',
    descripcion:
      'El pisto es un plato tradicional de La Mancha a base de verduras de la huerta. Similar al ratatouille francés pero con personalidad propia.',
    instrucciones:
      '1. Lavar y cortar todas las verduras en dados pequeños: calabacín, berenjena, pimientos y cebolla.\n2. Pelar y picar el ajo.\n3. Rallar o triturar los tomates.\n4. En una sartén amplia o cazuela, calentar el aceite de oliva.\n5. Sofreír la cebolla y el ajo a fuego medio durante 5 minutos.\n6. Añadir los pimientos y cocinar 5 minutos más.\n7. Incorporar el calabacín y la berenjena, cocinar 8-10 minutos.\n8. Añadir el tomate triturado y salar.\n9. Cocinar a fuego lento durante 20 minutos, removiendo de vez en cuando.\n10. El pisto debe quedar con las verduras tiernas pero no deshechas.',
    tiempoPreparacion: 20,
    tiempoCoccion: 40,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Verduras',
    estiloEspanol: true,
    region: 'Castilla-La Mancha',
    caloriasPorRacion: 150,
    proteinasPorRacion: 3,
    carbohidratosPorRacion: 14,
    grasasPorRacion: 9,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Calabacín', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Berenjena', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Pimiento rojo', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Pimiento verde', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Tomate', cantidad: 300, unidad: 'g', notas: 'triturado' },
      { alimentoNombre: 'Ajo', cantidad: 5, unidad: 'g', notas: '1 diente' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 40, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Ensalada César con pollo',
    descripcion:
      'Versión española de la clásica ensalada César, con pechuga de pollo a la plancha, queso y una salsa cremosa.',
    instrucciones:
      '1. Salpimentar la pechuga de pollo y cocinarla a la plancha con un poco de aceite hasta que esté dorada y bien hecha (unos 6-7 minutos por lado).\n2. Dejar reposar el pollo 5 minutos y cortarlo en tiras.\n3. Lavar y cortar la lechuga en trozos.\n4. Cortar el pan en dados pequeños y tostarlos en una sartén con un poco de aceite hasta que estén crujientes.\n5. Rallar o cortar el queso en láminas finas.\n6. Montar la ensalada: disponer la lechuga como base, colocar las tiras de pollo encima.\n7. Añadir los picatostes y el queso.\n8. Aliñar con aceite de oliva virgen extra y servir.',
    tiempoPreparacion: 15,
    tiempoCoccion: 15,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Ensaladas',
    estiloEspanol: false,
    region: null,
    caloriasPorRacion: 350,
    proteinasPorRacion: 32,
    carbohidratosPorRacion: 15,
    grasasPorRacion: 18,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: false,
    sinGluten: false,
    ingredientes: [
      { alimentoNombre: 'Pechuga de pollo', cantidad: 400, unidad: 'g' },
      { alimentoNombre: 'Lechuga', cantidad: 300, unidad: 'g' },
      { alimentoNombre: 'Queso fresco', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Pan blanco', cantidad: 80, unidad: 'g', notas: 'para picatostes' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Crema de calabacín',
    descripcion:
      'Crema suave y reconfortante de calabacín. Ligera, digestiva y perfecta como entrante o cena ligera.',
    instrucciones:
      '1. Pelar y picar la cebolla y la patata en trozos.\n2. Lavar y cortar el calabacín en rodajas (no es necesario pelarlo).\n3. En una olla, calentar el aceite de oliva y sofreír la cebolla hasta que esté transparente.\n4. Añadir la patata y el calabacín, y rehogar 3-4 minutos.\n5. Cubrir con agua o caldo de verduras.\n6. Cocinar a fuego medio durante 20 minutos hasta que todas las verduras estén tiernas.\n7. Triturar con batidora hasta obtener una crema fina.\n8. Añadir un chorrito de leche si se desea más cremosa.\n9. Rectificar de sal y servir con un hilo de aceite de oliva virgen extra.',
    tiempoPreparacion: 10,
    tiempoCoccion: 25,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Sopas y cremas',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 130,
    proteinasPorRacion: 4,
    carbohidratosPorRacion: 15,
    grasasPorRacion: 6,
    esAptoVegetariano: true,
    esAptoVegano: false,
    sinLactosa: false,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Calabacín', cantidad: 500, unidad: 'g' },
      { alimentoNombre: 'Patata', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Leche entera', cantidad: 100, unidad: 'ml' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 20, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Arroz con verduras',
    descripcion:
      'Arroz salteado con verduras de temporada. Un plato completo, colorido y muy versátil que se puede adaptar a las verduras disponibles.',
    instrucciones:
      '1. Cocinar el arroz según las instrucciones del paquete. Escurrir y reservar.\n2. Lavar y cortar todas las verduras: pimiento rojo en tiras, judías verdes en trozos, guisantes, calabacín en dados y zanahoria en rodajas finas.\n3. Picar el ajo.\n4. En un wok o sartén amplia, calentar el aceite de oliva.\n5. Saltear el ajo 30 segundos.\n6. Añadir la zanahoria y las judías verdes, cocinar 5 minutos.\n7. Incorporar el pimiento, el calabacín y los guisantes, cocinar 5 minutos más.\n8. Añadir el arroz cocido y mezclar bien con las verduras.\n9. Saltear todo junto 3-4 minutos a fuego fuerte.\n10. Salpimentar y servir caliente.',
    tiempoPreparacion: 15,
    tiempoCoccion: 25,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Arroces',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 290,
    proteinasPorRacion: 8,
    carbohidratosPorRacion: 48,
    grasasPorRacion: 7,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Arroz blanco', cantidad: 280, unidad: 'g' },
      { alimentoNombre: 'Pimiento rojo', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Judías verdes', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Guisantes', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Calabacín', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Zanahoria', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Ajo', cantidad: 5, unidad: 'g', notas: '1 diente' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 25, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Pechuga de pavo a la plancha',
    descripcion:
      'Pechuga de pavo a la plancha con guarnición de ensalada. Un plato alto en proteínas y bajo en grasa, ideal para una cena ligera y saludable.',
    instrucciones:
      '1. Salpimentar las pechugas de pavo.\n2. Calentar una plancha o sartén con un poco de aceite de oliva.\n3. Cocinar las pechugas de pavo 4-5 minutos por cada lado hasta que estén doradas y bien hechas.\n4. Mientras tanto, preparar la guarnición: lavar y cortar la lechuga, el tomate en rodajas y el pepino.\n5. Disponer la ensalada en los platos.\n6. Colocar la pechuga de pavo cortada en láminas sobre la ensalada.\n7. Aliñar con aceite de oliva virgen extra.\n8. Servir inmediatamente.',
    tiempoPreparacion: 10,
    tiempoCoccion: 10,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Carnes',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 200,
    proteinasPorRacion: 34,
    carbohidratosPorRacion: 5,
    grasasPorRacion: 5,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Pavo', cantidad: 500, unidad: 'g' },
      { alimentoNombre: 'Lechuga', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Tomate', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Pepino', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 20, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Hummus casero',
    descripcion:
      'Hummus cremoso elaborado con garbanzos cocidos. Un aperitivo saludable de inspiración mediterránea, perfecto para untar con pan o crudités.',
    instrucciones:
      '1. Si se usan garbanzos secos, ponerlos en remojo la noche anterior y cocerlos hasta que estén muy tiernos. También se pueden usar garbanzos de bote, bien escurridos.\n2. Pelar los ajos.\n3. Colocar los garbanzos en el vaso de la batidora o procesador.\n4. Añadir el ajo, el aceite de oliva virgen extra y un poco de agua de la cocción.\n5. Triturar hasta obtener una crema fina y homogénea.\n6. Si queda muy espeso, añadir un poco más de agua.\n7. Salpimentar al gusto.\n8. Servir en un plato con un chorrito de aceite de oliva por encima y unas semillas de chía como decoración.\n9. Acompañar con pan integral tostado o palitos de zanahoria.',
    tiempoPreparacion: 10,
    tiempoCoccion: 0,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Aperitivos',
    estiloEspanol: false,
    region: null,
    caloriasPorRacion: 220,
    proteinasPorRacion: 10,
    carbohidratosPorRacion: 24,
    grasasPorRacion: 10,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Garbanzos', cantidad: 400, unidad: 'g', notas: 'cocidos' },
      { alimentoNombre: 'Ajo', cantidad: 5, unidad: 'g', notas: '1 diente' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 40, unidad: 'ml' },
      { alimentoNombre: 'Semillas de chía', cantidad: 10, unidad: 'g', notas: 'para decorar' },
    ],
  },
  {
    nombre: 'Bowl de quinoa mediterráneo',
    descripcion:
      'Bowl nutritivo con quinoa como base, acompañado de verduras frescas, aguacate y frutos secos. Un plato moderno con ingredientes mediterráneos.',
    instrucciones:
      '1. Cocinar la quinoa: lavar bien bajo el grifo, poner en una olla con el doble de agua y cocinar 15 minutos hasta que absorba el agua. Dejar reposar tapada 5 minutos.\n2. Lavar y cortar el tomate en dados.\n3. Cortar el pepino en medias lunas.\n4. Cortar el aguacate en láminas.\n5. Lavar las espinacas frescas.\n6. Tostar ligeramente las almendras en una sartén sin aceite.\n7. Montar los bowls: poner una base de quinoa en cada plato.\n8. Disponer las espinacas, el tomate, el pepino y el aguacate de forma ordenada.\n9. Añadir las almendras tostadas y las aceitunas.\n10. Aliñar con aceite de oliva virgen extra y sal.\n11. Servir a temperatura ambiente.',
    tiempoPreparacion: 15,
    tiempoCoccion: 20,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Bowls',
    estiloEspanol: false,
    region: null,
    caloriasPorRacion: 380,
    proteinasPorRacion: 12,
    carbohidratosPorRacion: 35,
    grasasPorRacion: 22,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Quinoa', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Tomate', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Pepino', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Aguacate', cantidad: 150, unidad: 'g', notas: '1 aguacate' },
      { alimentoNombre: 'Espinacas', cantidad: 100, unidad: 'g', notas: 'frescas' },
      { alimentoNombre: 'Almendras', cantidad: 40, unidad: 'g' },
      { alimentoNombre: 'Aceitunas', cantidad: 40, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
    ],
  },
];
