export const recetasSeed2 = [
  {
    nombre: 'Paella valenciana',
    descripcion: 'El plato más emblemático de Valencia. Arroz con pollo, judías verdes y garrofón cocinado en paellera.',
    instrucciones: '1. Calentar aceite en la paellera y dorar el pollo troceado.\n2. Añadir judías verdes y sofreír 3 minutos.\n3. Agregar tomate rallado y sofreír hasta que oscurezca.\n4. Añadir pimentón, remover rápido y cubrir con agua.\n5. Hervir a fuego fuerte 20 minutos.\n6. Rectificar de sal, añadir el arroz distribuyéndolo bien.\n7. Cocinar a fuego fuerte 7 minutos y luego medio 13 minutos.\n8. Dejar reposar 5 minutos tapada con un paño.',
    tiempoPreparacion: 20,
    tiempoCoccion: 45,
    dificultad: 'media',
    raciones: 4,
    tipoComida: ['ALMUERZO'],
    categoria: 'Arroces',
    estiloEspanol: true,
    region: 'Valencia',
    caloriasPorRacion: 450,
    proteinasPorRacion: 28,
    carbohidratosPorRacion: 52,
    grasasPorRacion: 14,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Arroz blanco', cantidad: 320, unidad: 'g' },
      { alimentoNombre: 'Muslo de pollo', cantidad: 400, unidad: 'g' },
      { alimentoNombre: 'Judías verdes', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Tomate', cantidad: 100, unidad: 'g', notas: 'rallado' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 50, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Salmorejo cordobés',
    descripcion: 'Crema fría de tomate típica de Córdoba, más espesa que el gazpacho. Se sirve con virutas de jamón y huevo duro.',
    instrucciones: '1. Trocear los tomates maduros.\n2. Remojar el pan en agua y escurrir.\n3. Triturar tomates, pan, ajo y aceite de oliva hasta obtener crema fina.\n4. Colar para eliminar pieles y semillas.\n5. Refrigerar mínimo 2 horas.\n6. Servir con virutas de jamón serrano y huevo duro picado.',
    tiempoPreparacion: 15,
    tiempoCoccion: 0,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Sopas y cremas',
    estiloEspanol: true,
    region: 'Andalucía',
    caloriasPorRacion: 210,
    proteinasPorRacion: 8,
    carbohidratosPorRacion: 18,
    grasasPorRacion: 12,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: false,
    ingredientes: [
      { alimentoNombre: 'Tomate', cantidad: 600, unidad: 'g', notas: 'maduros' },
      { alimentoNombre: 'Pan blanco', cantidad: 100, unidad: 'g', notas: 'del día anterior' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 50, unidad: 'ml' },
      { alimentoNombre: 'Ajo', cantidad: 5, unidad: 'g', notas: '1 diente' },
      { alimentoNombre: 'Jamón serrano', cantidad: 40, unidad: 'g', notas: 'para decorar' },
      { alimentoNombre: 'Huevo', cantidad: 60, unidad: 'g', notas: '1 huevo duro' },
    ],
  },
  {
    nombre: 'Fabada asturiana',
    descripcion: 'Guiso tradicional de Asturias con fabes (alubias blancas), chorizo y morcilla. Plato reconfortante de invierno.',
    instrucciones: '1. Poner las alubias en remojo la noche anterior.\n2. Escurrir y colocar en olla grande cubiertas de agua fría.\n3. Añadir chorizo y morcilla enteros.\n4. Llevar a ebullición y bajar el fuego.\n5. Cocinar a fuego lento 2 horas, añadiendo agua fría si es necesario.\n6. Salar al final de la cocción.\n7. Dejar reposar 10 minutos antes de servir.\n8. Cortar los embutidos en rodajas y servir con las fabes.',
    tiempoPreparacion: 15,
    tiempoCoccion: 120,
    dificultad: 'media',
    raciones: 4,
    tipoComida: ['ALMUERZO'],
    categoria: 'Legumbres',
    estiloEspanol: true,
    region: 'Asturias',
    caloriasPorRacion: 520,
    proteinasPorRacion: 28,
    carbohidratosPorRacion: 45,
    grasasPorRacion: 26,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Alubias blancas', cantidad: 400, unidad: 'g' },
      { alimentoNombre: 'Chorizo', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Morcilla', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 20, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Pulpo a la gallega',
    descripcion: 'Plato típico gallego. Pulpo cocido servido sobre patata con pimentón y aceite de oliva.',
    instrucciones: '1. Congelar el pulpo previamente para ablandar la fibra.\n2. Hervir agua abundante en una olla grande.\n3. Asustar el pulpo sumergiéndolo 3 veces antes de dejarlo en el agua.\n4. Cocer 40-50 minutos hasta que esté tierno.\n5. Cocer las patatas peladas y cortadas en rodajas en el mismo agua.\n6. Cortar el pulpo con tijeras.\n7. Disponer las patatas en plato de madera, colocar el pulpo encima.\n8. Aliñar con aceite de oliva, pimentón y sal gorda.',
    tiempoPreparacion: 10,
    tiempoCoccion: 50,
    dificultad: 'media',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Pescados',
    estiloEspanol: true,
    region: 'Galicia',
    caloriasPorRacion: 280,
    proteinasPorRacion: 22,
    carbohidratosPorRacion: 20,
    grasasPorRacion: 12,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Pulpo', cantidad: 500, unidad: 'g' },
      { alimentoNombre: 'Patata', cantidad: 300, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 40, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Caldo gallego',
    descripcion: 'Sopa reconfortante gallega con grelos, patatas y alubias blancas.',
    instrucciones: '1. Poner las alubias en remojo la noche anterior.\n2. Cocer las alubias en agua fría durante 1 hora.\n3. Pelar y trocear las patatas, añadir a la olla.\n4. Lavar y trocear las acelgas, añadir.\n5. Cocinar 30 minutos más.\n6. Salar y añadir un chorrito de aceite de oliva al servir.',
    tiempoPreparacion: 15,
    tiempoCoccion: 90,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Sopas y cremas',
    estiloEspanol: true,
    region: 'Galicia',
    caloriasPorRacion: 280,
    proteinasPorRacion: 14,
    carbohidratosPorRacion: 38,
    grasasPorRacion: 8,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Alubias blancas', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Patata', cantidad: 300, unidad: 'g' },
      { alimentoNombre: 'Acelga', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 20, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Escalivada catalana',
    descripcion: 'Verduras asadas al horno típicas de Cataluña. Sencillo y lleno de sabor.',
    instrucciones: '1. Precalentar el horno a 200°C.\n2. Lavar las berenjenas, pimientos y cebollas.\n3. Colocar las verduras enteras en una bandeja de horno.\n4. Asar 45-60 minutos, dando la vuelta a mitad.\n5. Dejar enfriar envueltas en papel de periódico.\n6. Pelar y cortar en tiras.\n7. Aliñar con aceite de oliva virgen extra y sal.',
    tiempoPreparacion: 10,
    tiempoCoccion: 60,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Verduras',
    estiloEspanol: true,
    region: 'Cataluña',
    caloriasPorRacion: 140,
    proteinasPorRacion: 3,
    carbohidratosPorRacion: 12,
    grasasPorRacion: 9,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Berenjena', cantidad: 300, unidad: 'g' },
      { alimentoNombre: 'Pimiento rojo', cantidad: 300, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Revuelto de setas y gambas',
    descripcion: 'Revuelto cremoso de huevos con setas de temporada y gambas. Plato elegante y rápido.',
    instrucciones: '1. Pelar las gambas y reservar.\n2. Limpiar y laminar las setas.\n3. Picar el ajo finamente.\n4. Saltear las setas en aceite de oliva 5 minutos.\n5. Añadir las gambas y el ajo, cocinar 2 minutos.\n6. Batir los huevos ligeramente con sal.\n7. Verter los huevos sobre las setas y gambas.\n8. Remover suavemente a fuego bajo hasta que cuaje cremoso.\n9. Servir inmediatamente.',
    tiempoPreparacion: 10,
    tiempoCoccion: 10,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['CENA'],
    categoria: 'Platos principales',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 250,
    proteinasPorRacion: 22,
    carbohidratosPorRacion: 3,
    grasasPorRacion: 16,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Huevo', cantidad: 240, unidad: 'g', notas: '4 huevos' },
      { alimentoNombre: 'Gambas', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Champiñón', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Ajo', cantidad: 5, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 25, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Crema de calabaza',
    descripcion: 'Crema suave y dulce de calabaza, ideal para otoño e invierno. Reconfortante y ligera.',
    instrucciones: '1. Pelar y trocear la calabaza y la patata.\n2. Picar la cebolla.\n3. Sofreír la cebolla en aceite de oliva 5 minutos.\n4. Añadir calabaza y patata, cubrir con caldo de verduras.\n5. Cocinar 25 minutos hasta que estén tiernas.\n6. Triturar hasta obtener crema fina.\n7. Servir con un chorrito de aceite y semillas de calabaza.',
    tiempoPreparacion: 10,
    tiempoCoccion: 30,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Sopas y cremas',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 120,
    proteinasPorRacion: 3,
    carbohidratosPorRacion: 18,
    grasasPorRacion: 4,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Calabaza', cantidad: 500, unidad: 'g' },
      { alimentoNombre: 'Patata', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 20, unidad: 'ml' },
      { alimentoNombre: 'Semillas de calabaza', cantidad: 15, unidad: 'g', notas: 'para decorar' },
    ],
  },
  {
    nombre: 'Bacalao al pil-pil',
    descripcion: 'Plato emblemático del País Vasco. Bacalao en salsa emulsionada de ajo y aceite.',
    instrucciones: '1. Desalar el bacalao 48 horas cambiando el agua.\n2. Laminar los ajos y dorarlos en aceite de oliva suave. Reservar.\n3. En el mismo aceite templado, colocar el bacalao con la piel hacia arriba.\n4. Cocinar a fuego muy bajo 10 minutos.\n5. Retirar el bacalao y con el aceite de la cazuela hacer movimientos circulares para emulsionar la gelatina del bacalao.\n6. Ir añadiendo cucharadas de agua hasta lograr la salsa.\n7. Colocar el bacalao en la salsa y servir con los ajos.',
    tiempoPreparacion: 15,
    tiempoCoccion: 20,
    dificultad: 'dificil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Pescados',
    estiloEspanol: true,
    region: 'País Vasco',
    caloriasPorRacion: 320,
    proteinasPorRacion: 24,
    carbohidratosPorRacion: 2,
    grasasPorRacion: 24,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Bacalao fresco', cantidad: 500, unidad: 'g' },
      { alimentoNombre: 'Ajo', cantidad: 20, unidad: 'g', notas: '4-5 dientes' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 100, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Patatas bravas',
    descripcion: 'Tapa madrileña por excelencia. Patatas fritas con salsa brava picante.',
    instrucciones: '1. Pelar y cortar las patatas en dados grandes.\n2. Freír en aceite abundante hasta dorar.\n3. Para la salsa: sofreír cebolla y ajo picados.\n4. Añadir tomate rallado y pimentón.\n5. Cocinar 10 minutos y triturar.\n6. Servir las patatas calientes con la salsa por encima.',
    tiempoPreparacion: 15,
    tiempoCoccion: 25,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Aperitivos',
    estiloEspanol: true,
    region: 'Madrid',
    caloriasPorRacion: 280,
    proteinasPorRacion: 4,
    carbohidratosPorRacion: 32,
    grasasPorRacion: 15,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Patata', cantidad: 500, unidad: 'g' },
      { alimentoNombre: 'Tomate', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 50, unidad: 'g' },
      { alimentoNombre: 'Ajo', cantidad: 5, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 40, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Conejo al ajillo',
    descripcion: 'Receta tradicional castellana de conejo confitado con ajo y hierbas aromáticas.',
    instrucciones: '1. Trocear el conejo y salpimentar.\n2. Dorar en cazuela con aceite de oliva a fuego fuerte.\n3. Añadir los ajos enteros pelados.\n4. Bajar el fuego, añadir un chorro de vino blanco.\n5. Tapar y cocinar a fuego lento 45 minutos.\n6. Servir con su salsa.',
    tiempoPreparacion: 10,
    tiempoCoccion: 50,
    dificultad: 'media',
    raciones: 4,
    tipoComida: ['ALMUERZO'],
    categoria: 'Carnes',
    estiloEspanol: true,
    region: 'Castilla',
    caloriasPorRacion: 310,
    proteinasPorRacion: 28,
    carbohidratosPorRacion: 2,
    grasasPorRacion: 20,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Conejo', cantidad: 600, unidad: 'g' },
      { alimentoNombre: 'Ajo', cantidad: 30, unidad: 'g', notas: '8-10 dientes' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 50, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Ensalada de garbanzos',
    descripcion: 'Ensalada fresca y nutritiva con garbanzos, verduras crujientes y vinagreta de limón.',
    instrucciones: '1. Escurrir los garbanzos cocidos.\n2. Cortar tomate, pepino y cebolla en dados.\n3. Picar la rúcula.\n4. Mezclar todo en un bol.\n5. Aliñar con aceite de oliva, zumo de limón y sal.\n6. Servir a temperatura ambiente.',
    tiempoPreparacion: 15,
    tiempoCoccion: 0,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Ensaladas',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 260,
    proteinasPorRacion: 12,
    carbohidratosPorRacion: 30,
    grasasPorRacion: 10,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Garbanzos', cantidad: 400, unidad: 'g', notas: 'cocidos' },
      { alimentoNombre: 'Tomate', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Pepino', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 50, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
      { alimentoNombre: 'Limón', cantidad: 30, unidad: 'ml', notas: 'zumo' },
    ],
  },
  {
    nombre: 'Albóndigas en salsa de tomate',
    descripcion: 'Albóndigas caseras de ternera en salsa de tomate casera. Un clásico familiar.',
    instrucciones: '1. Mezclar la carne picada con huevo, pan rallado, ajo y perejil.\n2. Formar bolas con las manos.\n3. Freír las albóndigas en aceite hasta dorar.\n4. Para la salsa: sofreír cebolla y ajo picados.\n5. Añadir tomate rallado y cocinar 15 minutos.\n6. Incorporar las albóndigas a la salsa.\n7. Cocinar a fuego lento 20 minutos.',
    tiempoPreparacion: 20,
    tiempoCoccion: 40,
    dificultad: 'media',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Carnes',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 380,
    proteinasPorRacion: 28,
    carbohidratosPorRacion: 15,
    grasasPorRacion: 22,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: false,
    ingredientes: [
      { alimentoNombre: 'Ternera', cantidad: 400, unidad: 'g', notas: 'carne picada' },
      { alimentoNombre: 'Huevo', cantidad: 60, unidad: 'g', notas: '1 huevo' },
      { alimentoNombre: 'Pan blanco', cantidad: 30, unidad: 'g', notas: 'rallado' },
      { alimentoNombre: 'Tomate', cantidad: 400, unidad: 'g', notas: 'rallado' },
      { alimentoNombre: 'Cebolla', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Ajo', cantidad: 5, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Arroz negro con calamares',
    descripcion: 'Arroz teñido con tinta de calamar, típico del Mediterráneo español.',
    instrucciones: '1. Limpiar los calamares y reservar la tinta.\n2. Cortar los calamares en anillas.\n3. Sofreír cebolla y ajo picados.\n4. Añadir los calamares y cocinar 5 minutos.\n5. Añadir tomate rallado y la tinta disuelta en caldo.\n6. Incorporar el arroz y cubrir con caldo caliente.\n7. Cocinar 18-20 minutos sin remover.',
    tiempoPreparacion: 15,
    tiempoCoccion: 25,
    dificultad: 'media',
    raciones: 4,
    tipoComida: ['ALMUERZO'],
    categoria: 'Arroces',
    estiloEspanol: true,
    region: 'Valencia',
    caloriasPorRacion: 380,
    proteinasPorRacion: 18,
    carbohidratosPorRacion: 50,
    grasasPorRacion: 10,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Arroz blanco', cantidad: 300, unidad: 'g' },
      { alimentoNombre: 'Calamar', cantidad: 300, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Ajo', cantidad: 5, unidad: 'g' },
      { alimentoNombre: 'Tomate', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Tortilla de espinacas',
    descripcion: 'Variante saludable de la tortilla española, con espinacas frescas y cebolla.',
    instrucciones: '1. Lavar las espinacas y saltearlas brevemente.\n2. Picar la cebolla y sofreír hasta transparentar.\n3. Batir los huevos con sal.\n4. Mezclar espinacas y cebolla con los huevos.\n5. Cuajar en sartén antiadherente 4-5 minutos por cada lado.\n6. Servir templada.',
    tiempoPreparacion: 10,
    tiempoCoccion: 15,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Platos principales',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 180,
    proteinasPorRacion: 13,
    carbohidratosPorRacion: 4,
    grasasPorRacion: 12,
    esAptoVegetariano: true,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Huevo', cantidad: 240, unidad: 'g', notas: '4 huevos' },
      { alimentoNombre: 'Espinacas', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 20, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Sopa de ajo castellana',
    descripcion: 'Sopa tradicional castellana, humilde y reconfortante, con pan, ajo y pimentón.',
    instrucciones: '1. Laminar los ajos y dorar en aceite de oliva.\n2. Añadir el pan cortado en rebanadas finas.\n3. Agregar pimentón y remover rápido.\n4. Cubrir con caldo de pollo caliente.\n5. Cocinar 10 minutos.\n6. Cascar un huevo por persona sobre la sopa.\n7. Gratinar al horno 5 minutos.',
    tiempoPreparacion: 10,
    tiempoCoccion: 20,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['CENA'],
    categoria: 'Sopas y cremas',
    estiloEspanol: true,
    region: 'Castilla',
    caloriasPorRacion: 220,
    proteinasPorRacion: 12,
    carbohidratosPorRacion: 22,
    grasasPorRacion: 10,
    esAptoVegetariano: true,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: false,
    ingredientes: [
      { alimentoNombre: 'Ajo', cantidad: 20, unidad: 'g', notas: '4-5 dientes' },
      { alimentoNombre: 'Pan blanco', cantidad: 100, unidad: 'g', notas: 'del día anterior' },
      { alimentoNombre: 'Huevo', cantidad: 240, unidad: 'g', notas: '4 huevos' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Ensalada de lentejas',
    descripcion: 'Ensalada templada de lentejas con verduras frescas. Nutritiva y saciante.',
    instrucciones: '1. Cocer las lentejas 25 minutos. Escurrir y templar.\n2. Cortar tomate, pimiento rojo y cebolla en dados.\n3. Mezclar las lentejas con las verduras.\n4. Aliñar con aceite de oliva y vinagre.\n5. Servir templada o fría.',
    tiempoPreparacion: 10,
    tiempoCoccion: 25,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Ensaladas',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 290,
    proteinasPorRacion: 18,
    carbohidratosPorRacion: 38,
    grasasPorRacion: 8,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Lentejas', cantidad: 300, unidad: 'g' },
      { alimentoNombre: 'Tomate', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Pimiento rojo', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Dorada al horno con verduras',
    descripcion: 'Dorada fresca al horno sobre cama de verduras mediterráneas.',
    instrucciones: '1. Precalentar horno a 190°C.\n2. Cortar patatas, cebolla y tomate en rodajas.\n3. Disponer las verduras en fuente de horno.\n4. Aliñar con aceite, sal y hierbas.\n5. Hornear 15 minutos.\n6. Colocar la dorada limpia encima.\n7. Hornear 25 minutos más.',
    tiempoPreparacion: 15,
    tiempoCoccion: 40,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Pescados',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 290,
    proteinasPorRacion: 26,
    carbohidratosPorRacion: 22,
    grasasPorRacion: 10,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Dorada', cantidad: 500, unidad: 'g', notas: '2 doradas' },
      { alimentoNombre: 'Patata', cantidad: 300, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Tomate', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Wok de verduras con pollo',
    descripcion: 'Salteado rápido de verduras variadas con pollo. Saludable y colorido.',
    instrucciones: '1. Cortar la pechuga de pollo en tiras y salpimentar.\n2. Cortar todas las verduras en juliana fina.\n3. Calentar aceite en wok a fuego fuerte.\n4. Saltear el pollo 4-5 minutos. Reservar.\n5. Saltear las verduras 3-4 minutos (deben quedar crujientes).\n6. Incorporar el pollo de nuevo.\n7. Servir caliente.',
    tiempoPreparacion: 15,
    tiempoCoccion: 10,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Platos principales',
    estiloEspanol: false,
    region: null,
    caloriasPorRacion: 240,
    proteinasPorRacion: 30,
    carbohidratosPorRacion: 10,
    grasasPorRacion: 8,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Pechuga de pollo', cantidad: 400, unidad: 'g' },
      { alimentoNombre: 'Pimiento rojo', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Calabacín', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Zanahoria', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Brócoli', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 20, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Sardinas a la plancha',
    descripcion: 'Sardinas frescas a la plancha con ajo y perejil. Sencillo, sabroso y rico en omega-3.',
    instrucciones: '1. Limpiar las sardinas (quitar escamas y tripas).\n2. Salar ligeramente.\n3. Calentar la plancha a fuego fuerte.\n4. Cocinar las sardinas 2-3 minutos por cada lado.\n5. Servir con un picadillo de ajo y perejil con aceite de oliva.',
    tiempoPreparacion: 10,
    tiempoCoccion: 6,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Pescados',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 250,
    proteinasPorRacion: 28,
    carbohidratosPorRacion: 1,
    grasasPorRacion: 14,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Sardinas', cantidad: 500, unidad: 'g' },
      { alimentoNombre: 'Ajo', cantidad: 10, unidad: 'g', notas: '2 dientes' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 20, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Gazpacho de sandía',
    descripcion: 'Versión veraniega y refrescante del gazpacho tradicional con sandía.',
    instrucciones: '1. Trocear la sandía sin pepitas y el tomate.\n2. Triturar con pepino, aceite y vinagre.\n3. Colar si se desea.\n4. Refrigerar 2 horas mínimo.\n5. Servir muy frío.',
    tiempoPreparacion: 10,
    tiempoCoccion: 0,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Sopas y cremas',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 90,
    proteinasPorRacion: 1,
    carbohidratosPorRacion: 12,
    grasasPorRacion: 5,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Sandía', cantidad: 400, unidad: 'g' },
      { alimentoNombre: 'Tomate', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Pepino', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 20, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Cuscús con verduras',
    descripcion: 'Cuscús rápido con verduras salteadas y especias. Plato completo y ligero.',
    instrucciones: '1. Preparar el cuscús con agua hirviendo según indicaciones.\n2. Cortar calabacín, pimiento y zanahoria en dados.\n3. Saltear las verduras en aceite 8 minutos.\n4. Añadir garbanzos cocidos y calentar.\n5. Mezclar el cuscús con las verduras.\n6. Aliñar con aceite de oliva y servir.',
    tiempoPreparacion: 10,
    tiempoCoccion: 10,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Platos principales',
    estiloEspanol: false,
    region: null,
    caloriasPorRacion: 320,
    proteinasPorRacion: 12,
    carbohidratosPorRacion: 48,
    grasasPorRacion: 8,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: false,
    ingredientes: [
      { alimentoNombre: 'Cuscús', cantidad: 240, unidad: 'g' },
      { alimentoNombre: 'Calabacín', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Pimiento rojo', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Zanahoria', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Garbanzos', cantidad: 150, unidad: 'g', notas: 'cocidos' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 25, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Brochetas de pollo con verduras',
    descripcion: 'Brochetas coloridas de pollo marinado con verduras. Ideal para barbacoa o plancha.',
    instrucciones: '1. Cortar pollo en dados grandes.\n2. Marinar con aceite, ajo picado, limón y sal 30 minutos.\n3. Cortar pimiento y cebolla en trozos para ensartar.\n4. Montar las brochetas alternando pollo y verduras.\n5. Cocinar a la plancha o barbacoa 5-6 minutos por lado.\n6. Servir calientes.',
    tiempoPreparacion: 15,
    tiempoCoccion: 12,
    dificultad: 'facil',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Carnes',
    estiloEspanol: false,
    region: null,
    caloriasPorRacion: 230,
    proteinasPorRacion: 32,
    carbohidratosPorRacion: 6,
    grasasPorRacion: 8,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Pechuga de pollo', cantidad: 500, unidad: 'g' },
      { alimentoNombre: 'Pimiento rojo', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 25, unidad: 'ml' },
      { alimentoNombre: 'Limón', cantidad: 30, unidad: 'ml', notas: 'zumo' },
    ],
  },
  {
    nombre: 'Menestra de verduras',
    descripcion: 'Guiso navarro de verduras de temporada. Plato colorido y muy nutritivo.',
    instrucciones: '1. Cocer por separado alcachofas, judías verdes y guisantes.\n2. Picar cebolla y ajo.\n3. Sofreír cebolla y ajo en aceite.\n4. Añadir las verduras cocidas y zanahoria en rodajas.\n5. Rehogar todo junto 10 minutos.\n6. Salar y servir caliente.',
    tiempoPreparacion: 15,
    tiempoCoccion: 30,
    dificultad: 'media',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Verduras',
    estiloEspanol: true,
    region: 'Navarra',
    caloriasPorRacion: 160,
    proteinasPorRacion: 6,
    carbohidratosPorRacion: 18,
    grasasPorRacion: 7,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Alcachofa', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Judías verdes', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Guisantes', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Zanahoria', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Cebolla', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Ajo', cantidad: 5, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 25, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Tostada de aguacate con huevo',
    descripcion: 'Desayuno moderno y nutritivo. Pan integral con aguacate machacado y huevo escalfado.',
    instrucciones: '1. Tostar las rebanadas de pan integral.\n2. Machacar el aguacate con tenedor, sal y limón.\n3. Untar el aguacate en las tostadas.\n4. Escalfar los huevos en agua con vinagre.\n5. Colocar un huevo sobre cada tostada.\n6. Salpimentar y servir.',
    tiempoPreparacion: 5,
    tiempoCoccion: 5,
    dificultad: 'facil',
    raciones: 2,
    tipoComida: ['DESAYUNO'],
    categoria: 'Desayunos',
    estiloEspanol: false,
    region: null,
    caloriasPorRacion: 340,
    proteinasPorRacion: 14,
    carbohidratosPorRacion: 28,
    grasasPorRacion: 20,
    esAptoVegetariano: true,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: false,
    ingredientes: [
      { alimentoNombre: 'Pan integral', cantidad: 80, unidad: 'g', notas: '2 rebanadas' },
      { alimentoNombre: 'Aguacate', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Huevo', cantidad: 120, unidad: 'g', notas: '2 huevos' },
      { alimentoNombre: 'Limón', cantidad: 10, unidad: 'ml', notas: 'unas gotas' },
    ],
  },
  {
    nombre: 'Porridge de avena con frutas',
    descripcion: 'Gachas de avena cremosas con frutas frescas. Desayuno energético y saciante.',
    instrucciones: '1. Calentar la leche en un cazo.\n2. Añadir la avena y cocinar 5 minutos removiendo.\n3. Servir en bol.\n4. Cortar el plátano en rodajas y añadir fresas.\n5. Espolvorear con semillas de chía.\n6. Añadir un chorrito de miel si se desea.',
    tiempoPreparacion: 5,
    tiempoCoccion: 5,
    dificultad: 'facil',
    raciones: 2,
    tipoComida: ['DESAYUNO'],
    categoria: 'Desayunos',
    estiloEspanol: false,
    region: null,
    caloriasPorRacion: 310,
    proteinasPorRacion: 12,
    carbohidratosPorRacion: 50,
    grasasPorRacion: 7,
    esAptoVegetariano: true,
    esAptoVegano: false,
    sinLactosa: false,
    sinGluten: false,
    ingredientes: [
      { alimentoNombre: 'Avena', cantidad: 60, unidad: 'g' },
      { alimentoNombre: 'Leche semidesnatada', cantidad: 300, unidad: 'ml' },
      { alimentoNombre: 'Plátano', cantidad: 80, unidad: 'g', notas: '1 plátano' },
      { alimentoNombre: 'Fresa', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Semillas de chía', cantidad: 10, unidad: 'g' },
    ],
  },
  {
    nombre: 'Fideuá',
    descripcion: 'Plato marinero similar a la paella pero con fideos en lugar de arroz. Típico de Gandía.',
    instrucciones: '1. Hacer un fumet con cabezas de gamba y agua.\n2. Sofreír las gambas y calamares en aceite.\n3. Añadir tomate rallado y sofreír.\n4. Incorporar los fideos y tostar ligeramente.\n5. Añadir el fumet caliente.\n6. Cocinar 10-12 minutos hasta que los fideos absorban el caldo.\n7. Gratinar en el horno 2 minutos.',
    tiempoPreparacion: 15,
    tiempoCoccion: 25,
    dificultad: 'media',
    raciones: 4,
    tipoComida: ['ALMUERZO'],
    categoria: 'Arroces',
    estiloEspanol: true,
    region: 'Valencia',
    caloriasPorRacion: 360,
    proteinasPorRacion: 22,
    carbohidratosPorRacion: 42,
    grasasPorRacion: 12,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: true,
    sinGluten: false,
    ingredientes: [
      { alimentoNombre: 'Pasta', cantidad: 280, unidad: 'g', notas: 'fideos gruesos' },
      { alimentoNombre: 'Gambas', cantidad: 200, unidad: 'g' },
      { alimentoNombre: 'Calamar', cantidad: 150, unidad: 'g' },
      { alimentoNombre: 'Tomate', cantidad: 100, unidad: 'g', notas: 'rallado' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 30, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Berenjenas rellenas',
    descripcion: 'Berenjenas asadas rellenas de verduras y carne. Plato completo y sabroso.',
    instrucciones: '1. Cortar berenjenas por la mitad y vaciar parte de la pulpa.\n2. Picar la pulpa, cebolla, pimiento y tomate.\n3. Sofreír la carne picada con las verduras.\n4. Rellenar las berenjenas con la mezcla.\n5. Espolvorear con queso rallado.\n6. Hornear a 180°C durante 30 minutos.',
    tiempoPreparacion: 20,
    tiempoCoccion: 35,
    dificultad: 'media',
    raciones: 4,
    tipoComida: ['ALMUERZO', 'CENA'],
    categoria: 'Verduras',
    estiloEspanol: true,
    region: null,
    caloriasPorRacion: 280,
    proteinasPorRacion: 18,
    carbohidratosPorRacion: 14,
    grasasPorRacion: 16,
    esAptoVegetariano: false,
    esAptoVegano: false,
    sinLactosa: false,
    sinGluten: true,
    ingredientes: [
      { alimentoNombre: 'Berenjena', cantidad: 400, unidad: 'g', notas: '2 berenjenas' },
      { alimentoNombre: 'Ternera', cantidad: 200, unidad: 'g', notas: 'carne picada' },
      { alimentoNombre: 'Cebolla', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Pimiento rojo', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Tomate', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Queso mozzarella', cantidad: 60, unidad: 'g' },
      { alimentoNombre: 'Aceite de oliva virgen extra', cantidad: 20, unidad: 'ml' },
    ],
  },
  {
    nombre: 'Smoothie verde energético',
    descripcion: 'Batido verde nutritivo con espinacas, plátano y kiwi. Perfecto para empezar el día.',
    instrucciones: '1. Lavar las espinacas.\n2. Pelar el plátano y el kiwi.\n3. Triturar todo con la bebida de avena.\n4. Añadir semillas de chía.\n5. Servir frío.',
    tiempoPreparacion: 5,
    tiempoCoccion: 0,
    dificultad: 'facil',
    raciones: 2,
    tipoComida: ['DESAYUNO'],
    categoria: 'Desayunos',
    estiloEspanol: false,
    region: null,
    caloriasPorRacion: 170,
    proteinasPorRacion: 4,
    carbohidratosPorRacion: 32,
    grasasPorRacion: 3,
    esAptoVegetariano: true,
    esAptoVegano: true,
    sinLactosa: true,
    sinGluten: false,
    ingredientes: [
      { alimentoNombre: 'Espinacas', cantidad: 60, unidad: 'g' },
      { alimentoNombre: 'Plátano', cantidad: 80, unidad: 'g' },
      { alimentoNombre: 'Kiwi', cantidad: 100, unidad: 'g' },
      { alimentoNombre: 'Bebida de avena', cantidad: 200, unidad: 'ml' },
      { alimentoNombre: 'Semillas de chía', cantidad: 10, unidad: 'g' },
    ],
  },
];
